### ISSUE TITLE
Pivot fails to initialize after resuming on comments page

### ISSUE THREAD

**Issue by oliverspin** [soren121/yodel#89] opened 2015-04-19 23:03 UTC
If I view a comment, then put my phone to sleep while on the page. I come back to a blank feed page that I cannot refresh and I have to close the app and restart.

**Comment by soren121** [comment] 2015-04-19 23:16
Using 1.2.0.0 or 1.2.0.1? I thought I had fixed this. :disappointed:

Suspend/resume problems are hard to debug. I'll see what I can do.

**Comment by soren121** [comment] 2015-04-20 02:42
Also, the app should still work if you just press the back button.

**Comment by oliverspin** [comment] 2015-04-20 03:14
I just recreated the problem. I entered into a yak, made a comment, then put my phone to sleep for awhile. Later, I woke my phone back up and the yak appeared fine, but when I went back to the main feed it was blank and inactive. 


Let me know if you have any questions.






Sent from Surface





From: Nicholas Narsing
Sent: ‎Sunday‎, ‎April‎ ‎19‎, ‎2015 ‎7‎:‎42‎ ‎PM
To: soren121/yodel
Cc: Me





Also, the app should still work if you just press the back button.

**Comment by soren121** [comment] 2015-04-20 03:26
Oh, the main feed, I see. I did get that a couple times but couldn't reproduce it consistently. Thanks for the instructions.

**Comment by soren121** [comment] 2015-04-21 01:47
Fixed in 47eabb0. I'll be pushing an update to the Store with the fix shortly. Thanks for reporting it!

**Comment by oliverspin** [comment] 2015-04-21 01:48
Awesome, thanks!!

-----Original Message-----

**Comment by oliverspin** [comment] 2015-04-22 07:23
Hey, I hate to report bugs, but I also know it's helpful. 

-unable to open "Recent Yaks" and "recent replies" then back button doesn't work, then app crashes
-sometimes relaunching app after crash results in black screen


-----Original Message-----

**Comment by soren121** [comment] 2015-04-22 12:54
Don't feel bad about it. I wish more people would report bugs.

Are you using version 1.2.1.2?

Sent from my Windows Phone

-----Original Message-----

**Comment by oliverspin** [comment] 2015-04-22 15:05
Fixed. I wasn't up to date. Thanks!

-----Original Message-----

**Closed** 2015-04-23 05:14 UTC
Labels: bug, p2: important
